add calendar solution
js-tasks-ru/htmlcss-20211021_polina36 pull request #11
Opened 2021-11-07 16:50 UTC by polinabel

2021-11-07 16:51 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-11-10 20:14 UTC, GSemikozov requested changes

2021-11-10 20:14 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +    margin-bottom: calc(-100% / 7);
это точно нужно?)

2021-11-13 15:15 UTC, polinabel commented on 05-lection3/03-calendar/calendar.css
> +    margin-bottom: calc(-100% / 7);
ну, нет наверное) я просто скрыла пустой ряд ячеек, при этом грид остался квадратный

2021-11-13 15:18 UTC, polinabel commented on 05-lection3/03-calendar/calendar.css
> +    margin-bottom: calc(-100% / 7);
убрала

2021-11-13 15:18 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-11-13 15:27 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-11-14 12:40 UTC, GSemikozov approved these changes

2021-11-14 12:40 UTC, merged