add histogram solution
js-tasks-ru/htmlcss-20211021_polina36 pull request #7
Opened 2021-10-31 20:07 UTC by polinabel

2021-10-31 20:07 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-11-01 16:04 UTC, GSemikozov requested changes

2021-11-01 16:04 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    width: 100%;
по умолчанию блочный элемент и так растянется на 100%

2021-11-01 16:04 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    width: 5px;
лучше так не фиксировать и указать как в дизайне - flex-basis: 9px

2021-11-01 16:04 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    background-color: #4263EB;
а цвет взять из переменных

2021-11-02 20:11 UTC, polinabel commented on 04-lection2/01-histogram/histogram.css
> +    width: 100%;
убрала width

2021-11-02 20:11 UTC, polinabel commented on 04-lection2/01-histogram/histogram.css
> +    width: 5px;
пофикшено)

2021-11-02 20:11 UTC, polinabel commented on 04-lection2/01-histogram/histogram.css
> +    background-color: #4263EB;
исправила

2021-11-03 20:42 UTC, GSemikozov approved these changes

2021-11-03 20:42 UTC, merged